#before_install:
#  - npm i -g npm@version
sudo: false
cache:
  directories:
    - "node_modules"
language: node_js
node_js:
  - "node"

jobs:
  include:
    - stage: validity
      name: "Linting"
      script: npm run lint
    - stage: validity
      name: "Unit tests"
      script: npm run test-coverage && npm run report-coverage
    - stage: compile&test-e2e
      script: npm run test-e2e-latest
#    - stage: fossa
#      before_script:
#        - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
#      script:
#        - fossa init
#        - fossa analyze
#      after_success:
#        - cd src && fossa test

#notifications:
#  webhooks: https://app.fossa.io/hooks/travisci
